/*
 * File: app/store/StoreOpcaoPesquisaFuncionario.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('rsistemp.store.StoreOpcaoPesquisaFuncionario', {
    extend: 'Ext.data.Store',

    requires: [
        'rsistemp.model.ModelOpcaoPesquisaFuncionario',
        'Ext.data.proxy.Memory',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'StoreOpcaoPesquisaFuncionario',
            model: 'rsistemp.model.ModelOpcaoPesquisaFuncionario',
            proxy: {
                type: 'memory',
                data: {
                    dados: [
                        {
                            id: 1,
                            descricao: 'id'
                        },
                        {
                            id: 2,
                            descricao: 'nome'
                        },
                        {
                            id: 3,
                            descricao: 'cargo'
                        },
                        {
                            id: 4,
                            descricao: 'setor'
                        },
                        {
                            id: 5,
                            descricao: 'subsetor'
                        }
                    ]
                },
                reader: {
                    type: 'json',
                    rootProperty: 'dados'
                }
            }
        }, cfg)]);
    }
});