/*
 * File: app/store/StoreCargo.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('rsistemp.store.StoreCargo', {
    extend: 'Ext.data.Store',

    requires: [
        'rsistemp.model.ModelCargo',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'StoreCargo',
            model: 'rsistemp.model.ModelCargo',
            proxy: {
                type: 'ajax',
                url: '../../app/rsistemp.php?action=cargo&metodo=lista_cargo',
                reader: {
                    type: 'json',
                    rootProperty: 'dados'
                }
            }
        }, cfg)]);
    }
});