/*
 * File: app/view/gridFuncionario.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('rsistemp.view.gridFuncionario', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.gridfuncionario',

    requires: [
        'rsistemp.view.gridFuncionarioViewModel',
        'Ext.button.Button',
        'Ext.form.field.ComboBox',
        'Ext.view.Table',
        'Ext.grid.column.Date',
        'Ext.grid.column.Number',
        'Ext.grid.column.Template',
        'Ext.XTemplate',
        'Ext.grid.column.Action',
        'Ext.toolbar.Paging'
    ],

    viewModel: {
        type: 'gridfuncionario'
    },
    height: 720,
    itemId: 'gridFuncionario',
    scrollable: true,
    width: 1352,
    icon: 'resources/images/grid.png',
    title: 'Cadastro de Funcionário',
    columnLines: true,
    store: 'StoreFuncionario',
    defaultListenerScope: true,

    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            items: [
                {
                    xtype: 'button',
                    icon: '',
                    iconCls: 'x-fa fa-plus',
                    text: 'Novo',
                    listeners: {
                        click: 'onButtonClick'
                    }
                },
                {
                    xtype: 'button',
                    dock: 'top',
                    icon: 'resources/images/excel.png',
                    text: 'Exportar',
                    listeners: {
                        click: 'onButtonClick2'
                    }
                },
                {
                    xtype: 'button',
                    dock: 'top',
                    icon: 'resources/images/print.png',
                    text: 'Imprimir',
                    listeners: {
                        click: 'onButtonClick3'
                    }
                }
            ]
        },
        {
            xtype: 'toolbar',
            dock: 'top',
            items: [
                {
                    xtype: 'combobox',
                    itemId: 'opcaoPesquisarPor',
                    fieldLabel: 'Pesquisar',
                    labelWidth: 70,
                    name: 'pesquisarpor',
                    displayField: 'descricao',
                    store: 'StoreOpcaoPesquisaFuncionario',
                    valueField: 'id'
                },
                {
                    xtype: 'textfield',
                    itemId: 'pesquisarPor',
                    labelAlign: 'right',
                    labelWidth: 60,
                    name: 'pesquisarPor'
                },
                {
                    xtype: 'button',
                    iconCls: 'x-fa fa-search',
                    text: 'Pesquisar',
                    listeners: {
                        click: 'onButtonClick1'
                    }
                }
            ]
        },
        {
            xtype: 'pagingtoolbar',
            dock: 'bottom',
            width: 360,
            displayInfo: true,
            store: 'StoreFuncionario'
        }
    ],
    columns: [
        {
            xtype: 'gridcolumn',
            dataIndex: 'funcionario_id',
            text: 'Funcionario_ID'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'nome',
            text: 'Nome'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'sobrenome',
            text: 'Sobrenome'
        },
        {
            xtype: 'datecolumn',
            dataIndex: 'dtnascimento',
            text: 'Data Nascimento',
            format: 'd/m/Y'
        },
        {
            xtype: 'gridcolumn',
            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {

                return Ext.util.Format.number(value,'0,000.00').replace('.','*').replace(/,/g,'.').replace('*',',');
            },
            dataIndex: 'salario',
            text: 'Salário'
        },
        {
            xtype: 'numbercolumn',
            dataIndex: 'telefone',
            text: 'Telefone',
            format: '00'
        },
        {
            xtype: 'gridcolumn',
            width: '',
            dataIndex: 'idade',
            text: 'Idade'
        },
        {
            xtype: 'gridcolumn',
            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                if (value === 'F')
                {
                    return '<span style="color:' + 'pink' + ';">Feminino</span>';
                } else if (value === 'M') {
                    return '<span style="color:' + 'blue' + ';">Masculino</span>';
                }else{
                    return value;
                }
            },
            itemId: 'sexo',
            dataIndex: 'sexo',
            text: 'Sexo'
        },
        {
            xtype: 'templatecolumn',
            tpl: [
                '<a href="mailto:{email}">{email}</a>'
            ],
            dataIndex: 'email',
            text: 'Email'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'cargo_id',
            text: 'Cargo_id'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'desc_cargo',
            text: 'Desc Cargo'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'setor_id',
            text: 'Setor_id'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'desc_setor',
            text: 'Desc Setor'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'subsetor_id',
            text: 'Subsetor '
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'desc_subsetor',
            text: 'Desc Subsetor'
        },
        {
            xtype: 'actioncolumn',
            itemId: 'actionColumn_FuncionarioAlterar',
            width: 30,
            align: 'center',
            items: [
                {
                    handler: function(view, rowIndex, colIndex, item, e, record, row) {
                        // Criação do window
                        var win = Ext.create('rsistemp.view.WindowFuncionario', {
                            title: 'Alterar - Funcionario',
                        });

                        // Referenciando o formulário
                        var form = win.queryById('formulario');

                        // getForm - > fornece acessoa ao formulario
                        form.getForm().url = '../../app/rsistemp.php?action=funcionario&metodo=alterar_Funcionario';


                        // Carregar o Record no Formulário
                        form.getForm().findField('cargo_id').getStore().load({
                            callback: function( records, p2, p3) {
                                form.loadRecord(record);
                                // records[0].data.campo
                            }
                        });

                        form.getForm().findField('setor_id').getStore().load({
                            callback: function( records, p2, p3) {
                                form.loadRecord(record);
                                // records[0].data.campo
                            }
                        });

                        form.getForm().findField('subsetor_id').getStore().load({
                            callback: function( records, p2, p3) {
                                form.loadRecord(record);
                                // records[0].data.campo
                            }
                        });
                        //limpando novamente, para ter opção de trocar
                        //form.getForm().findField('funcionario_id').getStore().getProxy().extraParams = {};
                        // on -> é uma abreviação, um alias de Ext.Element.addListener
                        // definição de eventos em tempo de execução
                        win.on('close', function() {
                            // atualizar a grid
                            //view.getStore().removeAll();
                            view.getStore().load();
                        });

                        win.show();

                    },
                    icon: 'resources/images/edit.png',
                    iconCls: '',
                    tooltip: 'Editar'
                }
            ]
        },
        {
            xtype: 'actioncolumn',
            itemId: 'actionColumn_FuncionarioExcluir',
            width: 30,
            align: 'center',
            items: [
                {
                    handler: function(view, rowIndex, colIndex, item, e, record, row) {
                        Ext.Msg.show({
                            //titulo
                            title:'Excluir Registro?',
                            //messagem que ira aparecer quando abri a janela
                            msg: 'Tem certeza que deseja excluir o registro?',
                            //button yesno
                            buttons: Ext.Msg.YESNO,
                            //icone
                            icon: Ext.Msg.QUESTION,

                            //função do btn yes
                            fn : function(btn){
                                if ( btn == "yes"){
                                    //alert('Excluiu! - ' + record.get('nome'));

                                    //AJAX
                                    Ext.Ajax.request({
                                        //url: '../SISTEMA.php?action=cartao&metodo=_excluirCartao&id=' + record.get('id'), // VIA URL
                                        url: '../../app/rsistemp.php',
                                        params: { // VIA POST
                                            action: 'funcionario',
                                            metodo: 'excluir_Funcionario',
                                            funcionario_id: record.get('funcionario_id')
                                        },

                                        success: function(response){
                                            var resposta = Ext.JSON.decode(response.responseText);

                                            if(resposta.success===true)
                                            {
                                                rsistemp.getApplication().Msg(resposta.msg);
                                            }
                                            else if(resposta.success===false)
                                            {
                                                Ext.Msg.show({
                                                    title:'Atenção',
                                                    msg: resposta.msg,
                                                    buttons: Ext.Msg.OK,
                                                    icon: Ext.Msg.WARNING
                                                });
                                            }

                                            //Ext.Msg.alert('Status', resposta.msg);
                                            view.getStore().removeAll();
                                            view.getStore().load(); //LOAD NO GRID PARA ATUALIZAR O QUE É EXIBIDO!!!
                                        },
                                        failure: function(form, action) {
                                            //Ext.Msg.alert('Success', action.result.msg);
                                            Ext.Msg.show({
                                                title:'Atenção',
                                                msg: action.result.msg,
                                                buttons: Ext.Msg.OK,
                                                icon: Ext.Msg.WARNING
                                            });
                                        }
                                    });
                                }
                            }
                        });
                    },
                    icon: 'resources/images/delete.png',
                    tooltip: 'Excluir'
                }
            ]
        }
    ],

    onButtonClick: function(button, e, eOpts) {
        var win = Ext.create('rsistemp.view.WindowFuncionario');
        var grid = this;

        win.on('close', function() {
            //grid.getStore().removeAll();
            grid.getStore().load();
        });
        win.show();
    },

    onButtonClick2: function(button, e, eOpts) {

        var grid = Ext.ComponentQuery.query('[itemId=gridFuncionario]')[0];

        // debugger;

            var funcionario_id = this.queryById('funcionario_id');
            var nome = this.queryById('nome');

            var sobrenome = this.queryById('sobrenome');

            var dtnascimento = this.queryById('dtnascimento');
            var salario = this.queryById('salario');
            var telefone = this.queryById('telefone');

            var idade = this.queryById('idade');
            var sexo = this.queryById('sexo');

            var email = this.queryById('email');

            var cargo_id = this.queryById('cargo_id');
            var desc_cargo = this.queryById('desc_cargo');

            var setor_id = this.queryById('setor_id');
            var desc_setor = this.queryById('desc_setor');

            var subsetor_id = this.queryById('subsetor_id');
            var desc_subsetor = this.queryById('desc_subsetor');



        //Window
        //   var win = Ext.create('Ext.window.Window', {
        //         title : 'Baixando arquivo Excel',
        //         width : 400,
        //         height: 200,
        //         modal: true,
        //         layout: 'fit',
        //         maximizable: true
        //     });

            var tip  = Ext.create('Ext.tip.ToolTip', {
                target: Ext.getBody(),
                title: '<center><span style="color:' + 'red' + '; font-size:' + '18px' + ';font-weight:' + 'bold' + ';">Baixando arquivo excel</span></center>'

            });


        //comunicando com o php
        href = '../../app/rsistemp.php?action=funcionario&metodo=export_funcionario'+
                '&funcionario_id='+funcionario_id+
                '&nome='+nome+
                '&sobrenome='+sobrenome+
                '&dtnascimento='+dtnascimento+
                '&salario='+salario+
                '&telefone='+telefone+
                '&idade='+idade+
                '&sexo='+sexo+
                '&email='+email+
                '&cargo_id='+cargo_id+
                '&desc_cargo='+desc_cargo+
                '&setor_id='+setor_id+
                '&desc_setor='+desc_setor+
                '&subsetor_id='+subsetor_id+
                '&desc_subsetor='+desc_subsetor;

        tip.html = '<iframe src="'+href+'" name="principal" width="225px" height="10px" scrolling="auto" frameborder="0"></iframe>';

        //aparece na tela tooltip
            tip.showAt([0,0]);
            tip.alignTo(document, 't-t');
            tip.getEl().ghost('t', {
                easing: 'ease-in-out',
                duration: 5000,
                callback: function() {
                    Ext.destroy(tip);
                }
            });

        //aparece na tela window
        // win.show();


    },

    onButtonClick3: function(button, e, eOpts) {
        var grid = Ext.ComponentQuery.query('[itemId=gridFuncionario]')[0];


        // debugger;

                    var funcionario_id = this.queryById('funcionario_id');
                    var nome = this.queryById('nome');

                    var sobrenome = this.queryById('sobrenome');

                    var dtnascimento = this.queryById('dtnascimento');
                    var salario = this.queryById('salario');
                    var telefone = this.queryById('telefone');

                    var idade = this.queryById('idade');
                    var sexo = this.queryById('sexo');

                    var email = this.queryById('email');

                    var cargo_id = this.queryById('cargo_id');
                    var desc_cargo = this.queryById('desc_cargo');

                    var setor_id = this.queryById('setor_id');
                    var desc_setor = this.queryById('desc_setor');

                    var subsetor_id = this.queryById('subsetor_id');
                    var desc_subsetor = this.queryById('desc_subsetor');



                //Window
                //   var win = Ext.create('Ext.window.Window', {
                //         title : 'Baixando arquivo Excel',
                //         width : 400,
                //         height: 200,
                //         modal: true,
                //         layout: 'fit',
                //         maximizable: true
                //     });

        //             var win  = Ext.create('Ext.tip.ToolTip', {
        //                 target: Ext.getBody(),
        //                 title: '<center><span style="color:' + 'red' + '; font-size:' + '18px' + ';font-weight:' + 'bold' + ';">Baixando arquivo excel</span></center>'

        //             });


                //comunicando com o php
                href = '../../app/rsistemp.php?action=funcionario&metodo=_gerarRelatorioFuncionario'+
                        '&funcionario_id='+funcionario_id+
                        '&nome='+nome+
                        '&sobrenome='+sobrenome+
                        '&dtnascimento='+dtnascimento+
                        '&salario='+salario+
                        '&telefone='+telefone+
                        '&idade='+idade+
                        '&sexo='+sexo+
                        '&email='+email+
                        '&cargo_id='+cargo_id+
                        '&desc_cargo='+desc_cargo+
                        '&setor_id='+setor_id+
                        '&desc_setor='+desc_setor+
                        '&subsetor_id='+subsetor_id+
                        '&desc_subsetor='+desc_subsetor;

        //         win.html = '<iframe src="'+href+'" name="principal" width="225px" height="10px" scrolling="auto" frameborder="0"></iframe>';

        //         //aparece na tela tooltip
        //          win.showAt([0,0]);
        //             win.alignTo(document, 't-t');
        //             win.getEl().ghost('t', {
        //                 easing: 'ease-in-out',
        //                 duration: 5000,
        //                 callback: function() {
        //                     Ext.destroy(win);
        //                 }
        //             });


            var win = window.open(href, '_blank');
            if(win){
                //Browser has allowed it to be opened
                win.focus();
            }else{
                //Broswer has blocked it
                alert('Por favor, permita popups para este site');
            }

    },

    onButtonClick1: function(button, e, eOpts) {
        //Pegando os valores do comboBox
        var opcaoPesquisarPor = this.queryById('opcaoPesquisarPor').getValue();
        //Pegando os valores do text field
        var pesquisarPor = this.queryById('pesquisarPor').getValue();
        var Store = this.getStore();

        Store.getProxy().extraParams = {};

        Store.getProxy().extraParams.opcaoPesquisarPor = opcaoPesquisarPor;
        Store.getProxy().extraParams.pesquisarPor = pesquisarPor;
        //limpa todos os dados da store
        Store.removeAll();
        //atualiza a store
        Store.load();
    }

});