/*
 * File: app/view/gridSetor.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('rsistemp.view.gridSetor', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.gridsetor',

    requires: [
        'rsistemp.view.gridFuncionarioViewModel1',
        'Ext.button.Button',
        'Ext.form.field.ComboBox',
        'Ext.view.Table',
        'Ext.grid.column.Action',
        'Ext.toolbar.Paging'
    ],

    viewModel: {
        type: 'gridsetor'
    },
    height: 721,
    itemId: 'gridSetor',
    scrollable: true,
    width: 1352,
    icon: 'resources/images/grid.png',
    title: 'Cadastro de Setor',
    columnLines: true,
    store: 'StoreSetor',
    defaultListenerScope: true,

    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            items: [
                {
                    xtype: 'button',
                    icon: '',
                    iconCls: 'x-fa fa-plus',
                    text: 'Novo',
                    listeners: {
                        click: 'onButtonClick'
                    }
                },
                {
                    xtype: 'button',
                    dock: 'top',
                    icon: 'resources/images/excel.png',
                    text: 'Exportar',
                    listeners: {
                        click: 'onButtonClick2'
                    }
                }
            ]
        },
        {
            xtype: 'toolbar',
            dock: 'top',
            items: [
                {
                    xtype: 'combobox',
                    margins: '',
                    itemId: 'opcaoPesquisarPor',
                    fieldLabel: 'Pesquisar',
                    labelWidth: 70,
                    name: 'pesquisarpor',
                    displayField: 'descricao',
                    store: 'StoreOpcaoPesquisa',
                    valueField: 'id'
                },
                {
                    xtype: 'textfield',
                    margins: '0 0 0 30',
                    itemId: 'pesquisarPor',
                    fieldLabel: '',
                    labelAlign: 'right',
                    labelWidth: 60,
                    name: 'pesquisarPor'
                },
                {
                    xtype: 'button',
                    iconCls: 'x-fa fa-search',
                    text: 'Pesquisar',
                    listeners: {
                        click: 'onButtonClick1'
                    }
                }
            ]
        },
        {
            xtype: 'pagingtoolbar',
            dock: 'bottom',
            width: 360,
            displayInfo: true,
            store: 'StoreSetor'
        }
    ],
    columns: [
        {
            xtype: 'gridcolumn',
            dataIndex: 'setor_id',
            text: 'Setor_Id'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'desc_setor',
            text: 'Descrição'
        },
        {
            xtype: 'gridcolumn',
            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                if (value === 'A')
                {
                    return 'Ativo';
                } else if (value === 'I') {
                    return '<span style="color:' + 'red' + ';">INATIVO</span>';
                }else{
                    return value;
                }
            },
            dataIndex: 'status_setor',
            text: 'Status '
        },
        {
            xtype: 'actioncolumn',
            itemId: 'actionColumn_SetorAlterar',
            width: 40,
            align: 'center',
            items: [
                {
                    handler: function(view, rowIndex, colIndex, item, e, record, row) {
                        // Criação do window
                        var win = Ext.create('rsistemp.view.WindowSetor', {
                            title: 'Alterar - Setor',
                        });

                        // Referenciando o formulário
                        var form = win.queryById('setorFormulario');

                        // getForm - > fornece acessoa ao formulario
                        form.getForm().url = '../../app/rsistemp.php?action=setor&metodo=alterar_setor';

                        form.loadRecord(record);


                        win.on('close', function() {
                            // atualizar a grid
                            view.getStore().load();
                        });

                        win.show();
                    },
                    icon: 'resources/images/edit.png',
                    tooltip: 'Editar'
                }
            ]
        },
        {
            xtype: 'actioncolumn',
            width: 40,
            align: 'center',
            items: [
                {
                    handler: function(view, rowIndex, colIndex, item, e, record, row) {
                        Ext.Msg.show({
                            //titulo
                            title:'Excluir Registro?',
                            //messagem que ira aparecer quando abri a janela
                            msg: 'Tem certeza que deseja excluir o registro?',
                            //button yesno
                            buttons: Ext.Msg.YESNO,
                            //icone
                            icon: Ext.Msg.QUESTION,

                            //função do btn yes
                            fn : function(btn){
                                if ( btn == "yes"){
                                    //alert('Excluiu! - ' + record.get('nome'));

                                    //AJAX
                                    Ext.Ajax.request({
                                        //url: '../SISTEMA.php?action=cartao&metodo=_excluirCartao&id=' + record.get('id'), // VIA URL
                                        url: '../../app/rsistemp.php',
                                        params: { // VIA POST
                                            action: 'setor',
                                            metodo: 'excluir_setor',
                                            setor_id: record.get('setor_id')
                                        },

                                        success: function(response){
                                            var resposta = Ext.JSON.decode(response.responseText);

                                            if(resposta.success===true)
                                            {
                                                rsistemp.getApplication().Msg(resposta.msg);
                                            }
                                            else if(resposta.success===false)
                                            {
                                                Ext.Msg.show({
                                                    title:'Atenção',
                                                    msg: resposta.msg,
                                                    buttons: Ext.Msg.OK,
                                                    icon: Ext.Msg.WARNING
                                                });
                                            }

                                            //Ext.Msg.alert('Status', resposta.msg);
                                            view.getStore().removeAll();
                                            view.getStore().load(); //LOAD NO GRID PARA ATUALIZAR O QUE É EXIBIDO!!!
                                        },
                                        failure: function(form, action) {
                                            //Ext.Msg.alert('Success', action.result.msg);
                                            Ext.Msg.show({
                                                title:'Atenção',
                                                msg: action.result.msg,
                                                buttons: Ext.Msg.OK,
                                                icon: Ext.Msg.WARNING
                                            });
                                        }
                                    });
                                }
                            }
                        });
                    },
                    icon: 'resources/images/delete.png',
                    tooltip: 'Excluir'
                }
            ]
        }
    ],

    onButtonClick: function(button, e, eOpts) {
          var win = Ext.create('rsistemp.view.WindowSetor');
            var grid = this;

            win.on('close', function() {
                //grid.getStore().removeAll();
                grid.getStore().load();
            });
            win.show();
    },

    onButtonClick2: function(button, e, eOpts) {
        var grid = Ext.ComponentQuery.query('[itemId=gridSetor]')[0];


        // debugger;

            var setor_id = this.queryById('setor_id');
            var desc_setor = this.queryById('desc_setor');
            var status_setor = this.queryById('status_setor');



        //Tooltip
            var tip = Ext.create('Ext.tip.ToolTip', {
                target: Ext.getBody(),
                title: '<center><span style="color:' + 'red' + '; font-size:' + '18px' + ';font-weight:' + 'bold' + ';">Baixando arquivo excel</span></center>'

            });


        //comunicando com o php
        href = '../../app/rsistemp.php?action=setor&metodo=export_setor'+
                '&setor_id='+setor_id+
                '&desc_setor='+desc_setor+
                '&status_setor='+status_setor;

        tip.html = '<iframe src="'+href+'" name="principal" width="225px" height="10px" scrolling="auto" frameborder="0"></iframe>';

        //aparece na tela tooltip
            tip.showAt([0,0]);
            tip.alignTo(document, 't-t');
            tip.getEl().ghost('t', {
                easing: 'ease-in-out',
                duration: 5000,
                callback: function() {
                    Ext.destroy(tip);
                }
            });
    },

    onButtonClick1: function(button, e, eOpts) {
        //Pegando os valores do comboBox
        var opcaoPesquisarPor = this.queryById('opcaoPesquisarPor').getValue();
        //Pegando os valores do text field
        var pesquisarPor = this.queryById('pesquisarPor').getValue();
        var Store = this.getStore();

        Store.getProxy().extraParams = {};

        Store.getProxy().extraParams.opcaoPesquisarPor = opcaoPesquisarPor;
        Store.getProxy().extraParams.pesquisarPor = pesquisarPor;
        //limpa todos os dados da store
        Store.removeAll();
        //atualiza a store
        Store.load();
    }

});