/*
 * File: app/view/WindowCargoViewModel.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('rsistemp.view.WindowCargoViewModel', {
    extend: 'Ext.app.ViewModel',
    alias: 'viewmodel.windowcargo',

    requires: [
        'Ext.data.Store',
        'Ext.data.proxy.Memory'
    ],

    stores: {
        modelCargos: {
            model: 'rsistemp.model.ModelCargo',
            data: [
                {
                    cargo_id: 'consequatur',
                    desc_cargo: 'et',
                    status_cargo: 'nobis'
                },
                {
                    cargo_id: 'ut',
                    desc_cargo: 'neque',
                    status_cargo: 'expedita'
                },
                {
                    cargo_id: 'quia',
                    desc_cargo: 'distinctio',
                    status_cargo: 'officia'
                },
                {
                    cargo_id: 'eos',
                    desc_cargo: 'exercitationem',
                    status_cargo: 'maxime'
                },
                {
                    cargo_id: 'eum',
                    desc_cargo: 'voluptas',
                    status_cargo: 'quis'
                },
                {
                    cargo_id: 'sapiente',
                    desc_cargo: 'minima',
                    status_cargo: 'aspernatur'
                },
                {
                    cargo_id: 'ratione',
                    desc_cargo: 'ab',
                    status_cargo: 'impedit'
                },
                {
                    cargo_id: 'quas',
                    desc_cargo: 'praesentium',
                    status_cargo: 'doloremque'
                },
                {
                    cargo_id: 'consequatur',
                    desc_cargo: 'quia',
                    status_cargo: 'ducimus'
                },
                {
                    cargo_id: 'eius',
                    desc_cargo: 'qui',
                    status_cargo: 'quisquam'
                },
                {
                    cargo_id: 'quia',
                    desc_cargo: 'id',
                    status_cargo: 'aut'
                },
                {
                    cargo_id: 'et',
                    desc_cargo: 'omnis',
                    status_cargo: 'dignissimos'
                },
                {
                    cargo_id: 'est',
                    desc_cargo: 'sed',
                    status_cargo: 'voluptatem'
                },
                {
                    cargo_id: 'labore',
                    desc_cargo: 'ut',
                    status_cargo: 'debitis'
                },
                {
                    cargo_id: 'harum',
                    desc_cargo: 'dolorem',
                    status_cargo: 'tempore'
                },
                {
                    cargo_id: 'aut',
                    desc_cargo: 'quisquam',
                    status_cargo: 'dignissimos'
                },
                {
                    cargo_id: 'enim',
                    desc_cargo: 'maiores',
                    status_cargo: 'placeat'
                },
                {
                    cargo_id: 'cumque',
                    desc_cargo: 'mollitia',
                    status_cargo: 'nostrum'
                },
                {
                    cargo_id: 'culpa',
                    desc_cargo: 'non',
                    status_cargo: 'ea'
                },
                {
                    cargo_id: 'quis',
                    desc_cargo: 'distinctio',
                    status_cargo: 'possimus'
                },
                {
                    cargo_id: 'temporibus',
                    desc_cargo: 'voluptatem',
                    status_cargo: 'quaerat'
                },
                {
                    cargo_id: 'praesentium',
                    desc_cargo: 'est',
                    status_cargo: 'eos'
                },
                {
                    cargo_id: 'est',
                    desc_cargo: 'officiis',
                    status_cargo: 'est'
                },
                {
                    cargo_id: 'ea',
                    desc_cargo: 'odit',
                    status_cargo: 'nihil'
                },
                {
                    cargo_id: 'et',
                    desc_cargo: 'quas',
                    status_cargo: 'sed'
                },
                {
                    cargo_id: 'rerum',
                    desc_cargo: 'doloribus',
                    status_cargo: 'consequatur'
                },
                {
                    cargo_id: 'ipsam',
                    desc_cargo: 'quis',
                    status_cargo: 'autem'
                },
                {
                    cargo_id: 'nemo',
                    desc_cargo: 'maiores',
                    status_cargo: 'consequatur'
                },
                {
                    cargo_id: 'quidem',
                    desc_cargo: 'assumenda',
                    status_cargo: 'voluptas'
                },
                {
                    cargo_id: 'ipsum',
                    desc_cargo: 'ipsam',
                    status_cargo: 'sequi'
                }
            ],
            proxy: {
                type: 'memory'
            }
        }
    }

});