/*
 * File: app/view/WindowCargo.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('rsistemp.view.WindowCargo', {
    extend: 'Ext.window.Window',
    alias: 'widget.windowcargo',

    requires: [
        'rsistemp.view.WindowCargoViewModel',
        'Ext.toolbar.Toolbar',
        'Ext.toolbar.Fill',
        'Ext.button.Button',
        'Ext.form.Panel',
        'Ext.form.field.Hidden',
        'Ext.form.field.Text',
        'Ext.form.RadioGroup',
        'Ext.form.field.Radio'
    ],

    viewModel: {
        type: 'windowcargo'
    },
    modal: true,
    flex: 1,
    height: 160,
    width: 380,
    layout: 'fit',
    icon: 'resources/images/grid.png',
    title: 'Cadastro de cargo',
    defaultListenerScope: true,

    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'bottom',
            items: [
                {
                    xtype: 'tbfill'
                },
                {
                    xtype: 'button',
                    icon: 'resources/images/save.gif',
                    text: 'Salvar',
                    listeners: {
                        click: 'onButtonClick'
                    }
                },
                {
                    xtype: 'button',
                    icon: 'resources/images/cross.png',
                    text: 'Fechar',
                    listeners: {
                        click: 'onButtonClick1'
                    }
                }
            ]
        }
    ],
    items: [
        {
            xtype: 'form',
            anchor: '100%',
            flex: 1,
            height: 180,
            itemId: 'cargoFormulario',
            bodyPadding: 10,
            bodyStyle: '10',
            title: '',
            url: '../../app/rsistemp.php?action=cargo&metodo=inserir_cargo',
            items: [
                {
                    xtype: 'hiddenfield',
                    fieldLabel: 'Cargo Id',
                    name: 'cargo_id'
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    flex: 1,
                    width: '',
                    fieldLabel: 'Cargo',
                    labelWidth: 50,
                    msgTarget: 'side',
                    name: 'desc_cargo',
                    allowBlank: false,
                    minLength: 2
                },
                {
                    xtype: 'radiogroup',
                    anchor: '100%',
                    itemId: 'status_cargo',
                    width: 400,
                    fieldLabel: 'Status',
                    fieldDefaults: {
                        name: 'status'
                    },
                    columns: '1',
                    simpleValue: true,
                    items: [
                        {
                            xtype: 'radiofield',
                            itemId: 'ativo',
                            name: 'status_cargo',
                            boxLabel: 'Ativo',
                            checked: true,
                            inputValue: 'A'
                        },
                        {
                            xtype: 'radiofield',
                            itemId: 'inativo',
                            name: 'status_cargo',
                            boxLabel: 'Inativo',
                            inputValue: 'I'
                        }
                    ]
                }
            ]
        }
    ],

    onButtonClick: function(button, e, eOpts) {
        var formPrincipal = this.down('form');//this - Janela -
        var id   = formPrincipal.getForm().findField('cargo_id').getValue();
        var win = this;
        var campo01 = formPrincipal.getForm().findField('desc_cargo');
        var grid = Ext.ComponentQuery.query('grid[itemId=gridCargo]')[0];

        if( formPrincipal.getForm().isValid() ){
            formPrincipal.getForm().submit({
                success: function(form, action) {
                    //Ext.Msg.alert('Success', action.result.msg);
                    if (id === '' || id === null) {
                        formPrincipal.getForm().reset(true);
                        if (win.carregaStore===true)
                        {
                            grid. getStore().removeAll();
                            grid.getStore().load();
                        }
                        campo01.focus(false,true);
                        rsistemp.getApplication().Msg('Registro incluído com sucesso');

                    } else {
                        win.close();
                    }
                },
                failure: function(form, action) {
        //          Ext.Msg.alert('Success','Registro incluído com sucesso!');
                    //Ext.Msg.alert('Success', action.result.msg);
                    Ext.Msg.show({
                        title:'Atenção',
                        msg: action.result.msg,
                        buttons: Ext.Msg.OK,
                        icon: Ext.Msg.WARNING
                    });
                }
            });
        }
    },

    onButtonClick1: function(button, e, eOpts) {
        this.close();
    }

});