/*
 * File: app/view/WindowSetorViewModel.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('rsistemp.view.WindowSetorViewModel', {
    extend: 'Ext.app.ViewModel',
    alias: 'viewmodel.windowsetor',

    requires: [
        'Ext.data.Store',
        'Ext.data.proxy.Memory'
    ],

    stores: {
        modelSetors: {
            model: 'rsistemp.model.ModelSetor',
            data: [
                {
                    setor_id: 'ut',
                    desc_setor: 'qui',
                    status_setor: 'aperiam'
                },
                {
                    setor_id: 'quia',
                    desc_setor: 'ducimus',
                    status_setor: 'natus'
                },
                {
                    setor_id: 'consequatur',
                    desc_setor: 'natus',
                    status_setor: 'et'
                },
                {
                    setor_id: 'tempore',
                    desc_setor: 'sint',
                    status_setor: 'est'
                },
                {
                    setor_id: 'velit',
                    desc_setor: 'aspernatur',
                    status_setor: 'officia'
                },
                {
                    setor_id: 'quod',
                    desc_setor: 'repudiandae',
                    status_setor: 'eum'
                },
                {
                    setor_id: 'rem',
                    desc_setor: 'consectetur',
                    status_setor: 'ab'
                },
                {
                    setor_id: 'doloribus',
                    desc_setor: 'illum',
                    status_setor: 'tempora'
                },
                {
                    setor_id: 'aut',
                    desc_setor: 'molestiae',
                    status_setor: 'cupiditate'
                },
                {
                    setor_id: 'porro',
                    desc_setor: 'corporis',
                    status_setor: 'et'
                },
                {
                    setor_id: 'aspernatur',
                    desc_setor: 'repellendus',
                    status_setor: 'fugit'
                },
                {
                    setor_id: 'esse',
                    desc_setor: 'ut',
                    status_setor: 'suscipit'
                },
                {
                    setor_id: 'magni',
                    desc_setor: 'qui',
                    status_setor: 'eligendi'
                },
                {
                    setor_id: 'expedita',
                    desc_setor: 'dolores',
                    status_setor: 'voluptatum'
                },
                {
                    setor_id: 'aut',
                    desc_setor: 'soluta',
                    status_setor: 'exercitationem'
                },
                {
                    setor_id: 'vel',
                    desc_setor: 'magnam',
                    status_setor: 'vero'
                },
                {
                    setor_id: 'et',
                    desc_setor: 'sit',
                    status_setor: 'omnis'
                },
                {
                    setor_id: 'consequatur',
                    desc_setor: 'voluptates',
                    status_setor: 'corporis'
                },
                {
                    setor_id: 'nemo',
                    desc_setor: 'illum',
                    status_setor: 'laborum'
                },
                {
                    setor_id: 'quia',
                    desc_setor: 'ducimus',
                    status_setor: 'quasi'
                },
                {
                    setor_id: 'quia',
                    desc_setor: 'assumenda',
                    status_setor: 'ea'
                },
                {
                    setor_id: 'mollitia',
                    desc_setor: 'ex',
                    status_setor: 'et'
                },
                {
                    setor_id: 'nihil',
                    desc_setor: 'ut',
                    status_setor: 'et'
                },
                {
                    setor_id: 'ut',
                    desc_setor: 'fuga',
                    status_setor: 'expedita'
                },
                {
                    setor_id: 'numquam',
                    desc_setor: 'quaerat',
                    status_setor: 'delectus'
                },
                {
                    setor_id: 'dolorum',
                    desc_setor: 'porro',
                    status_setor: 'dolore'
                },
                {
                    setor_id: 'omnis',
                    desc_setor: 'rerum',
                    status_setor: 'eos'
                },
                {
                    setor_id: 'sunt',
                    desc_setor: 'consequuntur',
                    status_setor: 'excepturi'
                },
                {
                    setor_id: 'magni',
                    desc_setor: 'labore',
                    status_setor: 'expedita'
                },
                {
                    setor_id: 'non',
                    desc_setor: 'in',
                    status_setor: 'et'
                }
            ],
            proxy: {
                type: 'memory'
            }
        }
    }

});