/*
 * File: app/model/ModelFuncionario.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('rsistemp.model.ModelFuncionario', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.String',
        'Ext.data.field.Date',
        'Ext.data.field.Number'
    ],

    idProperty: 'funcionario_id',

    fields: [
        {
            name: 'funcionario_id'
        },
        {
            type: 'string',
            name: 'nome'
        },
        {
            type: 'string',
            name: 'sobrenome'
        },
        {
            type: 'int',
            name: 'idade'
        },
        {
            name: 'sexo'
        },
        {
            type: 'date',
            name: 'dtnascimento',
            dateFormat: 'Y-m-d'
        },
        {
            type: 'float',
            name: 'salario'
        },
        {
            type: 'string',
            name: 'telefone'
        },
        {
            type: 'string',
            name: 'email'
        },
        {
            name: 'cargo_id'
        },
        {
            name: 'desc_cargo'
        },
        {
            name: 'setor_id'
        },
        {
            name: 'desc_setor'
        },
        {
            name: 'subsetor_id'
        },
        {
            name: 'desc_subsetor'
        }
    ]
});