/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

// @require @packageOverrides
Ext.Loader.setConfig({

});


Ext.application({
    models: [
        'ModelFuncionario',
        'ModelOpcaoPesquisa',
        'ModelCargo',
        'ModelSetor',
        'ModelSubSetor',
        'ModelOpcaoPesquisaFuncionario',
        'ModelOpcaoPesquisaSubsetor'
    ],
    stores: [
        'StoreFuncionario',
        'StoreOpcaoPesquisa',
        'StoreCargo',
        'StoreSetor',
        'StoreSubSetor',
        'StoreOpcaoPesquisaFuncionario',
        'StoreOpcaoPesquisaSubsetor'
    ],
    views: [
        'MyViewport',
        'gridFuncionario',
        'WindowFuncionario',
        'gridCargo',
        'WindowCargo',
        'gridSetor',
        'WindowSetor',
        'gridSubSetor',
        'WindowSubsetor'
    ],
    controllers: [
        'MyController'
    ],
    name: 'rsistemp',

    requires: [
        'Ext.Loader'
    ],

    Msg: function(title) {
            var tip = Ext.create('Ext.tip.ToolTip', {
                target: Ext.getBody(),
                html: title,
                bodyStyle: 'font-size:18px;font-weight:bold;color: red;'
            });


            tip.showAt([0,0]);
            tip.alignTo(document, 't-t');
            //tip.getEl().slideIn('t').pause(1).ghost("t", {remove:true});
            tip.getEl().ghost('t', {
                easing: 'easeOut',
                duration: 4000,
                callback: function() {
                    Ext.destroy(tip);
                }
            });
    },

    launch: function() {
        Ext.create('rsistemp.view.MyViewport');
    }

});
